# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69575869cec18c7019776a1f1cf2079d70d23fe4f980736b17250d0fd6d8aa1f7ac79cdef32f8df68ed49edaf2ba24d0e313c80b56bfcfd7531c5b761378b26

test:
  secret_key_base: 3412caf41543131fbe9be385b8aa36f291d6d0bc64762a3bb976589652e36913c588b3deef219781509ac2dcb4278f9f762dadaa2e6fb68ee2e27d98570ecae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
